### ISSUE TITLE
麻烦老大能支持一下 2019 年么

### ISSUE THREAD

**Issue by conanx2008** [bastengao/chinese-holidays-node#3]
麻烦老大能支持一下 2019 年么？我的项目一直在用你的模块，很感谢你的无私贡献。

**Comment by bastengao** [comment]
其实我计划做在线更新数据的特性，但是一直拖着没搞完。

**Comment by bastengao** [comment]
https://github.com/bastengao/chinese-holidays-node/releases/tag/v0.4.0 已发布，更新包就可以用了。

**Comment by conanx2008** [comment]
真速度啊！必须赞你一个！

**Comment by bastengao** [comment]
@conanx2008 v1.0.0 支持了在线更新数据，再也不同担心数据会不同步了。

**Comment by conanx2008** [comment]
你太强大了，马上更新。

**Comment by conanx2008** [comment]
我发现一个问题，我通过 npm install chinese-holidays 方式安装后，里面少了book.js这个文件，运行后就报错了。但源码中是有个这文件的。

**Comment by bastengao** [comment]
@conanx2008 我推了个新版本 v1.0.1，再试下看看。

**Comment by conanx2008** [comment]
更新后完美，现在又可以愉快的用你的模块了！
