### ISSUE TITLE
typescript 中怎样使用，安装后使用时一直报错

### ISSUE THREAD

**Issue by sunshaobin** [bastengao/chinese-holidays-node#4]

**Comment by bastengao** [comment]
TypeScript 中还没有试过，能告诉下是怎们操作的呢？

**Comment by sunshaobin** [comment]
> TypeScript 中还没有试过，能告诉下是怎们操作的呢？

import chineseHolidays from 'chinese-holidays';
chineseHolidays.ready((book, err) => {
      if (err != null) {
        return;
      }

      const date = new Date(2016, 0, 1);
      // 是否休假(含正常的周六、周日)
      book.isHoliday(date);
      // true

      // 是否是工作日(含节假日的调休)
      book.isWorkingday(date);
      // fase

      // 列出已知的节假日
      book.all().forEach(holiday => {
        console.log(holiday.name);
        console.log(
          holiday.days().map(date => {
            return moment(date).format('YYYY-MM-DD');
          }),
        );
      });
      // 元旦
      // ["2016-01-01", "2016-01-02", "2016-01-03"]
      // ...

      // 列出所有的特殊日子(节假日和调休)
      book.events().forEach(event => {
        console.log(event.name, event.days(), event.isHoliday(), event.isWorkingday());
      });
    });
×
Unhandled Rejection (TypeError): fs.existsSync is not a function
是必须通过require来引入吗？在前端通过import 引入报这个错

**Comment by bastengao** [comment]
你的运行环境是 node 还是浏览器？

**Comment by sunshaobin** [comment]
> 你的运行环境是 node 还是浏览器？
在浏览器中执行时报的错

**Comment by bastengao** [comment]
暂时还不支持在浏览器中运行，目前只能在 node 环境中运行。

**Comment by sunshaobin** [comment]
> 暂时还不支持在浏览器中运行，目前只能在 node 环境中运行。

好的，感谢
