### ISSUE TITLE
获取数据的接口已经下线

### ISSUE THREAD

**Issue by chuyik** [bastengao/chinese-holidays-node#7]
这个接口不能访问了 [http://bastengao.coding.me/chinese-holidays-data/data](http://bastengao.coding.me/chinese-holidays-data/data)

**Comment by bastengao** [comment]
马上安排，新域名。

**Comment by bastengao** [comment]
新的数据地址在这里 http://chinese-holidays-data.basten.me/index.html ，稍后我对库进行升级。

**Comment by bastengao** [comment]
v1.2.1 已经发布。
